# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [ ]:
print("Hello World!")

In [3]:

import pandas as pd
from pathlib import Path

file_path = Path("data") / "SBALoanData-LoanApproval_DefaultAnalysis.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows and columns:", df.shape)

display(df.head())

Dataset loaded successfully!
Number of rows and columns: (5000, 18)

,ApprovalDate,ApprovalFY,ProcessingMethod,GrossApproval,SBAGuaranteedApproval,InitialInterestRate,FixedorVariableInterestInd,TermInMonths,NaicsDescription,ProjectState,BusinessType,BusinessAge,LoanStatus,PaidInFullDate,ChargeOffDate,GrossChargeOffAmount,RevolverStatus,JobsSupported
0,27-05-2022,2022,SBA Express Program,50000,25000.0,5.99,F,60,Other Management Consulting Services,MN,CORPORATION,Existing or more than 2 years old,EXEMPT,NaN,NaN,0.0,N,1
1,24-03-2025,2025,Preferred Lenders Program,210000,157500.0,7.75,V,120,Interior Design Services,NM,CORPORATION,Existing or more than 2 years old,EXEMPT,NaN,NaN,0.0,N,3
2,25-03-2025,2025,Preferred Lenders Program,187700,140775.0,8.50,F,120,Web Search Portals and All Other Information S...,MO,CORPORATION,Existing or more than 2 years old,EXEMPT,NaN,NaN,0.0,N,0
3,13-08-2021,2021,Preferred Lenders Program,554000,498600.0,5.75,V,120,Full-Service Restaurants,NC,CORPORATION,"Startup, Loan Funds will Open Business",EXEMPT,NaN,NaN,0.0,N,36
4,15-12-2020,2021,Preferred Lenders Program,140000,119000.0,5.00,F,120,Family Clothing Stores,WI,CORPORATION,"Startup, Loan Funds will Open Business",EXEMPT,NaN,NaN,0.0,N,3

In [2]:

from pathlib import Path

print("Current project location:")
print(Path.cwd())

print("\nFiles and folders in project:")
for item in Path.cwd().iterdir():
    print(item.name)

print("\nFiles inside data folder:")
data_folder = Path("data")

if data_folder.exists():
    for item in data_folder.iterdir():
        print(repr(item.name))
else:
    print("data folder not found in current location")

Current project location:
C:\Users\user\PycharmProjects\SBA_Loan_Analysis

Files and folders in project:
.idea
.venv
data
models
README.md
sample.ipynb

Files inside data folder:
'SBALoanData-LoanApproval_DefaultAnalysis.csv'

In [4]:

# 1. Check dataset size
print("Dataset Shape:", df.shape)

# 2. Check column names and data types
print("\n--- Column Information ---")
df.info()

# 3. Check missing values
print("\n--- Missing Values ---")
print(df.isnull().sum())

# 4. Check duplicate rows
print("\n--- Duplicate Rows ---")
print("Duplicate rows:", df.duplicated().sum())

# 5. Get summary statistics
print("\n--- Numerical Summary ---")
display(df.describe())

Dataset Shape: (5000, 18)

--- Column Information ---
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApprovalDate                5000 non-null   str
 1   ApprovalFY                  5000 non-null   int64
 2   ProcessingMethod            5000 non-null   str
 3   GrossApproval               5000 non-null   int64
 4   SBAGuaranteedApproval       5000 non-null   float64
 5   InitialInterestRate         5000 non-null   float64
 6   FixedorVariableInterestInd  5000 non-null   str
 7   TermInMonths                5000 non-null   int64
 8   NaicsDescription            5000 non-null   str
 9   ProjectState                5000 non-null   str
 10  BusinessType                4999 non-null   str
 11  BusinessAge                 4998 non-null   str
 12  LoanStatus                  5000 non-null   str
 13  PaidInFullDate              878 non-null    str
 14  ChargeOffDate               89 non-null     str
 15  GrossChargeOffAmount        5000 non-null   float64
 16  RevolverStatus              5000 non-null   str
 17  JobsSupported               5000 non-null   int64
dtypes: float64(3), int64(4), str(11)
memory usage: 703.3 KB

--- Missing Values ---
ApprovalDate                     0
ApprovalFY                       0
ProcessingMethod                 0
GrossApproval                    0
SBAGuaranteedApproval            0
InitialInterestRate              0
FixedorVariableInterestInd       0
TermInMonths                     0
NaicsDescription                 0
ProjectState                     0
BusinessType                     1
BusinessAge                      2
LoanStatus                       0
PaidInFullDate                4122
ChargeOffDate                 4911
GrossChargeOffAmount             0
RevolverStatus                   0
JobsSupported                    0
dtype: int64

--- Duplicate Rows ---
Duplicate rows: 0

--- Numerical Summary ---

,ApprovalFY,GrossApproval,SBAGuaranteedApproval,InitialInterestRate,TermInMonths,GrossChargeOffAmount,JobsSupported
count,5000.000000,5.000000e+03,5.000000e+03,5000.000000,5000.000000,5.000000e+03,5000.000000
mean,2023.204400,5.138609e+05,3.876239e+05,8.862155,138.046400,2.174867e+03,10.413000
std,1.888103,8.428467e+05,6.534235e+05,2.703483,69.782612,2.949291e+04,18.440001
min,2020.000000,5.000000e+03,2.500000e+03,0.000000,4.000000,0.000000e+00,0.000000
25%,2022.000000,5.600000e+04,3.891875e+04,6.250000,120.000000,0.000000e+00,2.000000
50%,2023.000000,1.980000e+05,1.275000e+05,9.260000,120.000000,0.000000e+00,5.000000
75%,2025.000000,5.000000e+05,3.750000e+05,10.750000,120.000000,0.000000e+00,11.000000
max,2026.000000,5.000000e+06,4.500000e+06,15.500000,318.000000,1.119416e+06,281.000000

In [5]:

# Check loan status categories
print("--- Loan Status Counts ---")
display(df["LoanStatus"].value_counts(dropna=False))

# Check missing dates by loan status
print("\n--- Loan Status vs Paid In Full Date ---")
display(pd.crosstab(
    df["LoanStatus"],
    df["PaidInFullDate"].isna(),
    margins=True
))

print("\n--- Loan Status vs Charge-Off Date ---")
display(pd.crosstab(
    df["LoanStatus"],
    df["ChargeOffDate"].isna(),
    margins=True
))

# Check the few missing business details
print("\n--- Missing Business Details ---")
display(df[df["BusinessType"].isna() | df["BusinessAge"].isna()])

--- Loan Status Counts ---

LoanStatus
EXEMPT    3119
P I F      878
CANCLD     642
COMMIT     272
CHGOFF      89
Name: count, dtype: int64

--- Loan Status vs Paid In Full Date ---

PaidInFullDate  False  True   All
LoanStatus
CANCLD              0   642   642
CHGOFF              0    89    89
COMMIT              0   272   272
EXEMPT              0  3119  3119
P I F             878     0   878
All               878  4122  5000

--- Loan Status vs Charge-Off Date ---

ChargeOffDate  False  True   All
LoanStatus
CANCLD             0   642   642
CHGOFF            89     0    89
COMMIT             0   272   272
EXEMPT             0  3119  3119
P I F              0   878   878
All               89  4911  5000

--- Missing Business Details ---

,ApprovalDate,ApprovalFY,ProcessingMethod,GrossApproval,SBAGuaranteedApproval,InitialInterestRate,FixedorVariableInterestInd,TermInMonths,NaicsDescription,ProjectState,BusinessType,BusinessAge,LoanStatus,PaidInFullDate,ChargeOffDate,GrossChargeOffAmount,RevolverStatus,JobsSupported
1973,04-03-2020,2020,SBA Express Program,5000,2500.0,9.25,V,81,Commercial Screen Printing,NC,CORPORATION,NaN,CHGOFF,NaN,27-07-2023,4602.94,Y,0
2275,13-11-2019,2020,Preferred Lenders Program,1436000,1077000.0,5.55,F,169,"All Other Professional, Scientific, and Techni...",SC,CORPORATION,NaN,EXEMPT,NaN,NaN,0.00,N,9
3329,11-12-2025,2026,Preferred Lenders Program,2600000,1950000.0,9.50,V,120,Other Personal Care Services,AZ,NaN,Change of Ownership,EXEMPT,NaN,NaN,0.00,N,14

In [6]:

# Create a separate copy for cleaning
df_clean = df.copy()

# Convert date columns to proper datetime format
date_columns = [
    "ApprovalDate",
    "PaidInFullDate",
    "ChargeOffDate"
]

for col in date_columns:
    df_clean[col] = pd.to_datetime(
        df_clean[col],
        format="%d-%m-%Y",
        errors="coerce"
    )

# Check date conversion
print("--- Date Data Types ---")
print(df_clean[date_columns].dtypes)

# Check missing business details
print("\n--- Missing Values Before Handling ---")
print(df_clean[["BusinessType", "BusinessAge"]].isnull().sum())

# Fill missing categorical details with "Unknown"
df_clean["BusinessType"] = df_clean["BusinessType"].fillna("Unknown")
df_clean["BusinessAge"] = df_clean["BusinessAge"].fillna("Unknown")

# Verify cleaning
print("\n--- Missing Values After Handling ---")
print(df_clean[["BusinessType", "BusinessAge"]].isnull().sum())

print("\nCleaned dataset shape:", df_clean.shape)

--- Date Data Types ---
ApprovalDate      datetime64[us]
PaidInFullDate    datetime64[us]
ChargeOffDate     datetime64[us]
dtype: object

--- Missing Values Before Handling ---
BusinessType    1
BusinessAge     2
dtype: int64

--- Missing Values After Handling ---
BusinessType    0
BusinessAge     0
dtype: int64

Cleaned dataset shape: (5000, 18)

In [7]:

# Count loans by status
loan_status_counts = (
    df_clean["LoanStatus"]
    .value_counts()
    .rename_axis("LoanStatus")
    .reset_index(name="LoanCount")
)

# Calculate percentage of total loans
loan_status_counts["Percentage"] = (
    loan_status_counts["LoanCount"] / len(df_clean) * 100
).round(2)

print("--- Loan Status Summary ---")
display(loan_status_counts)

# Calculate total charge-off amount
total_charge_off = df_clean["GrossChargeOffAmount"].sum()

print(
    "\nTotal Gross Charge-Off Amount: $",
    f"{total_charge_off:,.2f}"
)

# Count loans with a positive charge-off amount
charge_off_loans = (
    df_clean["GrossChargeOffAmount"] > 0
).sum()

print("Loans with positive charge-off amount:", charge_off_loans)

--- Loan Status Summary ---

  LoanStatus  LoanCount  Percentage
0     EXEMPT       3119       62.38
1      P I F        878       17.56
2     CANCLD        642       12.84
3     COMMIT        272        5.44
4     CHGOFF         89        1.78

Total Gross Charge-Off Amount: $ 10,874,334.62
Loans with positive charge-off amount: 89

In [8]:

# Analyze loan approvals by financial year
yearly_analysis = (
    df_clean.groupby("ApprovalFY")
    .agg(
        TotalLoans=("ApprovalFY", "size"),
        TotalApprovalAmount=("GrossApproval", "sum"),
        AverageLoanAmount=("GrossApproval", "mean"),
        TotalJobsSupported=("JobsSupported", "sum")
    )
    .reset_index()
)

# Format amounts for readability
yearly_analysis["AverageLoanAmount"] = (
    yearly_analysis["AverageLoanAmount"].round(2)
)

yearly_analysis["TotalApprovalAmount"] = (
    yearly_analysis["TotalApprovalAmount"].round(2)
)

print("--- Yearly Loan Approval Analysis ---")
display(yearly_analysis)

--- Yearly Loan Approval Analysis ---

,ApprovalFY,TotalLoans,TotalApprovalAmount,AverageLoanAmount,TotalJobsSupported
0,2020,550,287757400,523195.27,5884
1,2021,678,448488100,661486.87,7679
2,2022,563,313674100,557147.60,6423
3,2023,713,347253900,487032.12,7854
4,2024,913,411209700,450393.98,8558
5,2025,1071,515800800,481606.72,10532
6,2026,512,245120500,478750.98,5135

In [9]:

print("Number of yearly records:", len(yearly_analysis))
print(yearly_analysis.to_string(index=False))

Number of yearly records: 7
 ApprovalFY  TotalLoans  TotalApprovalAmount  AverageLoanAmount  TotalJobsSupported
       2020         550            287757400          523195.27                5884
       2021         678            448488100          661486.87                7679
       2022         563            313674100          557147.60                6423
       2023         713            347253900          487032.12                7854
       2024         913            411209700          450393.98                8558
       2025        1071            515800800          481606.72               10532
       2026         512            245120500          478750.98                5135

In [10]:

# Compare processing methods
method_analysis = (
    df_clean.groupby("ProcessingMethod")
    .agg(
        TotalLoans=("ProcessingMethod", "size"),
        TotalApprovalAmount=("GrossApproval", "sum"),
        ChargeOffLoans=("LoanStatus", lambda s: (s == "CHGOFF").sum()),
        ChargeOffAmount=("GrossChargeOffAmount", "sum")
    )
    .reset_index()
)

method_analysis["ChargeOffPercentage"] = (
    method_analysis["ChargeOffLoans"]
    / method_analysis["TotalLoans"] * 100
).round(2)

print("--- Processing Method Analysis ---")
display(method_analysis)

--- Processing Method Analysis ---

,ProcessingMethod,TotalLoans,TotalApprovalAmount,ChargeOffLoans,ChargeOffAmount,ChargeOffPercentage
0,7(a) WCP,2,600000,0,0.00,0.00
1,7a General,276,236104300,4,2450114.42,1.45
2,7a with EWCP,1,1653200,0,0.00,0.00
3,Builders CAPLine,4,8300000,0,0.00,0.00
4,Community Advantage Initiative,41,7061200,3,501584.01,7.32
5,Community Advantage Recovery Loan,1,212800,0,0.00,0.00
6,Contract CAPLine,2,1600000,0,0.00,0.00
7,Export Express,2,850000,0,0.00,0.00
8,International Trade Loans,16,34365500,0,0.00,0.00
9,Preferred Lenders Program,2750,2047924300,29,5542961.32,1.05
10,Preferred Lenders with EWCP,6,19000000,0,0.00,0.00
11,Preferred Lenders with WCP,1,995000,0,0.00,0.00
12,SBA Express Program,1888,198243200,53,2379674.87,2.81
13,Seasonal CAPLine,1,5000000,0,0.00,0.00
14,Working Capital CAPLine,9,7395000,0,0.00,0.00

In [11]:

# Analyze loan status by business age
business_age_analysis = (
    df_clean.groupby("BusinessAge")
    .agg(
        TotalLoans=("LoanStatus", "size"),
        ChargeOffLoans=(
            "LoanStatus",
            lambda s: (s == "CHGOFF").sum()
        ),
        TotalApprovalAmount=("GrossApproval", "sum"),
        ChargeOffAmount=("GrossChargeOffAmount", "sum")
    )
    .reset_index()
)

business_age_analysis["ChargeOffPercentage"] = (
    business_age_analysis["ChargeOffLoans"]
    / business_age_analysis["TotalLoans"] * 100
).round(2)

print("--- Business Age Analysis ---")
display(
    business_age_analysis.sort_values(
        "ChargeOffPercentage",
        ascending=False
    )
)

--- Business Age Analysis ---

,BusinessAge,TotalLoans,ChargeOffLoans,TotalApprovalAmount,ChargeOffAmount,ChargeOffPercentage
5,Unknown,2,1,1441000,4602.94,50.00
4,Unanswered,50,2,11612100,49474.86,4.00
3,"Startup, Loan Funds will Open Business",801,17,397099700,1819847.62,2.12
2,New Business or 2 years or less,778,14,368117800,978138.55,1.80
1,Existing or more than 2 years old,2847,49,1217747400,6097827.82,1.72
0,Change of Ownership,522,6,573286500,1924442.83,1.15

In [12]:

print(
    business_age_analysis[
        [
            "BusinessAge",
            "TotalLoans",
            "ChargeOffLoans",
            "TotalApprovalAmount",
            "ChargeOffAmount",
            "ChargeOffPercentage"
        ]
    ].to_string(index=False)
)

                           BusinessAge  TotalLoans  ChargeOffLoans  TotalApprovalAmount  ChargeOffAmount  ChargeOffPercentage
                   Change of Ownership         522               6            573286500       1924442.83                 1.15
     Existing or more than 2 years old        2847              49           1217747400       6097827.82                 1.72
       New Business or 2 years or less         778              14            368117800        978138.55                 1.80
Startup, Loan Funds will Open Business         801              17            397099700       1819847.62                 2.12
                            Unanswered          50               2             11612100         49474.86                 4.00
                               Unknown           2               1              1441000          4602.94                50.00

In [13]:

from pathlib import Path

# Create output folder
output_folder = Path("data/processed")
output_folder.mkdir(parents=True, exist_ok=True)

# Save cleaned dataset
output_file = output_folder / "sba_loan_cleaned.csv"

df_clean.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File location:", output_file.resolve())
print("Rows and columns:", df_clean.shape)

# Verify the saved file
df_check = pd.read_csv(output_file)

print("Saved file verification:", df_check.shape)

Cleaned dataset saved successfully!
File location: C:\Users\user\PycharmProjects\SBA_Loan_Analysis\data\processed\sba_loan_cleaned.csv
Rows and columns: (5000, 18)
Saved file verification: (5000, 18)

In [14]:

# Final data quality checks

print("--- Dataset Shape ---")
print(df_clean.shape)

print("\n--- Duplicate Rows ---")
print(df_clean.duplicated().sum())

print("\n--- Missing Values ---")
print(df_clean.isnull().sum())

print("\n--- Invalid or Suspicious Values ---")
print("Non-positive loan approvals:",
      (df_clean["GrossApproval"] <= 0).sum())

print("Negative charge-off amounts:",
      (df_clean["GrossChargeOffAmount"] < 0).sum())

print("Negative jobs supported:",
      (df_clean["JobsSupported"] < 0).sum())

print("\n--- Loan Status Counts ---")
print(df_clean["LoanStatus"].value_counts())

--- Dataset Shape ---
(5000, 18)

--- Duplicate Rows ---
0

--- Missing Values ---
ApprovalDate                     0
ApprovalFY                       0
ProcessingMethod                 0
GrossApproval                    0
SBAGuaranteedApproval            0
InitialInterestRate              0
FixedorVariableInterestInd       0
TermInMonths                     0
NaicsDescription                 0
ProjectState                     0
BusinessType                     0
BusinessAge                      0
LoanStatus                       0
PaidInFullDate                4122
ChargeOffDate                 4911
GrossChargeOffAmount             0
RevolverStatus                   0
JobsSupported                    0
dtype: int64

--- Invalid or Suspicious Values ---
Non-positive loan approvals: 0
Negative charge-off amounts: 0
Negative jobs supported: 0

--- Loan Status Counts ---
LoanStatus
EXEMPT    3119
P I F      878
CANCLD     642
COMMIT     272
CHGOFF      89
Name: count, dtype: int64

In [6]:
print("Shape:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nInvalid approvals:",
      (df_clean["GrossApproval"] <= 0).sum())

print("Negative charge-off amounts:",
      (df_clean["GrossChargeOffAmount"] < 0).sum())

print("Negative jobs supported:",
      (df_clean["JobsSupported"] < 0).sum())

Shape: (5000, 18)
Duplicate rows: 0

Missing values:
ApprovalDate                     0
ApprovalFY                       0
ProcessingMethod                 0
GrossApproval                    0
SBAGuaranteedApproval            0
InitialInterestRate              0
FixedorVariableInterestInd       0
TermInMonths                     0
NaicsDescription                 0
ProjectState                     0
BusinessType                     0
BusinessAge                      0
LoanStatus                       0
PaidInFullDate                4122
ChargeOffDate                 4911
GrossChargeOffAmount             0
RevolverStatus                   0
JobsSupported                    0
dtype: int64

Invalid approvals: 0
Negative charge-off amounts: 0
Negative jobs supported: 0